/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    class MyClass {
        int val;

        MyClass(int val) {
            val = val;
        }

        @Override
        public int hashCode() {
            System.out.printf("hashCode is invoked.\n");
            return val;
        }

        @Override
        public boolean equals(Object obj) {
            System.out.printf("equals is invoked.\n");

            if (obj instanceof MyClass) {

                if (this.hashCode() != obj.hashCode())
                    return false;

                return this.val == ((MyClass)obj).val;
            }

            return false;
        }
    }

    @Test public void testSomeLibraryMethod() {
        MyClass c1 = new MyClass(1);
        MyClass c2 = new MyClass(2);

        c1.equals(c2);
    }
}
